emit:
  - "@typespec/openapi3"

options:
  "@typespec/openapi3":
    file-type: yaml
    emitter-output-dir: "{project-root}/openapi"
    output-file: "openapi.yaml"
    openapi-versions:
      - "3.0.0"
